# Use container-based infrastructure
sudo: false

language: scala

scala:
- 2.11.6

jdk:
- oraclejdk8

env:
  global:
    - SONATYPE_USERNAME=scalapenos
    - secure: "TODO result of travis encrypt -r scalapenos/stamina SONATYPE_PASSWORD=password"

script: "sbt ++$TRAVIS_SCALA_VERSION clean test"

after_success: "sbt publish"
