sudo: false
language: scala

scala:
  - 2.11.11
  - 2.12.4
  - 2.13.1

jdk:
  - openjdk8

stages:
  - name: test
  - name: release
    if: "((branch = master AND type = push) OR (tag IS present)) AND NOT fork"

before_install:
  - git fetch --tags

jobs:
  include:
  - stage: release
    script: sbt ci-release
